// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkF_m12PUKBrthaKX9eDjbsC5oM81ISA8',
    appId: '1:348728758965:web:454fe3a7b9e5c034f0e4fc',
    messagingSenderId: '348728758965',
    projectId: 'otp0-ee689',
    authDomain: 'otp0-ee689.firebaseapp.com',
    storageBucket: 'otp0-ee689.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUs6-R7w8Y7nGzbCHRTuG6e6iuYaDF_oQ',
    appId: '1:348728758965:android:b9cbfea441901266f0e4fc',
    messagingSenderId: '348728758965',
    projectId: 'otp0-ee689',
    storageBucket: 'otp0-ee689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxZ61yBLb6Gv_kMZ_OSI5MirpqnITqLA',
    appId: '1:348728758965:ios:bd2a60dad487803af0e4fc',
    messagingSenderId: '348728758965',
    projectId: 'otp0-ee689',
    storageBucket: 'otp0-ee689.appspot.com',
    iosBundleId: 'com.example.batchloreskitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsxZ61yBLb6Gv_kMZ_OSI5MirpqnITqLA',
    appId: '1:348728758965:ios:bd2a60dad487803af0e4fc',
    messagingSenderId: '348728758965',
    projectId: 'otp0-ee689',
    storageBucket: 'otp0-ee689.appspot.com',
    iosBundleId: 'com.example.batchloreskitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkF_m12PUKBrthaKX9eDjbsC5oM81ISA8',
    appId: '1:348728758965:web:cd6e0f60a1d61dc1f0e4fc',
    messagingSenderId: '348728758965',
    projectId: 'otp0-ee689',
    authDomain: 'otp0-ee689.firebaseapp.com',
    storageBucket: 'otp0-ee689.appspot.com',
  );
}